Add bookings
KurakinPavel/java-shareit pull request #2
Opened 2024-05-10 07:23 UTC by KurakinPavel

2024-05-10 21:53 UTC, db-exp requested changes

2024-05-10 21:53 UTC, db-exp commented on src/main/resources/schema.sql
> +    EMAIL   VARCHAR(512) NOT NULL,
много 512 - вряд ли больше 100 нужно

2024-05-10 21:53 UTC, db-exp commented on src/main/resources/schema.sql
> +    TEXT       VARCHAR(1024) NOT NULL,
лучше не называть поле созвучно типу данных

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/User.java
>       protected int id;
в модели базы bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public void remove(@PathVariable Integer userId) {
в модели базы bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserService.java
в модели базы идентификаторы  bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserService.java
>  public class UserService {
хорошо бы transactional проставить, там, где только чтение с readonly = true

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    public UserDto(Integer id, String name, String email) {
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoForBookingOut.java
> +    protected Integer id;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>      protected int id;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoWithBookingInformation.java
> +    protected Integer id;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoForBookingOut.java
> +    protected Integer id;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>          this.id = id;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/CommentDtoOut.java
> +    protected int id;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/CommentDtoIn.java
> +    protected Integer id;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemService.java
>  public class ItemService {
Хорошо бы Transactional проставить, там, где только чтение с readonly = true

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemService.java
в модели базы идентификаторы bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private final BookingRepository bookingStorage;
лучше пользоваться "чужими" сервисами, а не репозиториями напрямую

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllByOwnerId(int ownerId);
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    List<Comment> findAllByItemId(int itemId);
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    protected int id;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoForOut.java
> +    protected Integer id;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoForIn.java
> +    protected Integer itemId;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/Item.java
>      protected int id;
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      public ItemDto add(@RequestHeader("X-Sharer-User-Id") Integer ownerId,
в модели базы идентификатор bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
в модели базы идентификаторы bigint = long. То есть либо тут менять либо там

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (item.getOwner().getId() == bookerId) throw new NoSuchElementException("Владелец не может бронировать свои вещи");
лучше не писать однострочники с if - очень легко ошибиться, лучше со скобками

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        } catch (EntityNotFoundException e) {
такие ошибки лучше даже на уровне репозитория ловить - они со слоя хранения

2024-05-10 21:53 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +public class BookingService {
хорошо бы добавить Transactional и там, где только чтение c readOnly = true

2024-05-11 08:52 UTC, KurakinPavel commented on src/main/resources/schema.sql
> +    EMAIL   VARCHAR(512) NOT NULL,
Поправил.

2024-05-11 08:57 UTC, KurakinPavel commented on src/main/resources/schema.sql
> +    TEXT       VARCHAR(1024) NOT NULL,
Исправил.

2024-05-11 09:01 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/user/User.java
>       protected int id;
Исправил.

2024-05-11 09:01 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public void remove(@PathVariable Integer userId) {
Исправил.

2024-05-11 09:02 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/user/UserService.java
Исправил.

2024-05-11 09:02 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    public UserDto(Integer id, String name, String email) {
Исправил.

2024-05-11 09:02 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoForBookingOut.java
> +    protected Integer id;
Исправил.

2024-05-11 09:02 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>      protected int id;
Исправил.

2024-05-11 09:02 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoWithBookingInformation.java
> +    protected Integer id;
Исправил.

2024-05-11 09:02 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoForBookingOut.java
> +    protected Integer id;
Исправил.

2024-05-11 09:03 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>          this.id = id;
Исправил.

2024-05-11 09:03 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/dto/CommentDtoOut.java
> +    protected int id;
Исправил.

2024-05-11 09:03 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/dto/CommentDtoIn.java
> +    protected Integer id;
Исправил.

2024-05-11 09:04 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/ItemService.java
Исправил.

2024-05-11 09:04 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllByOwnerId(int ownerId);
Исправил.

2024-05-11 09:04 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    List<Comment> findAllByItemId(int itemId);
Исправил.

2024-05-11 09:04 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    protected int id;
Исправил.

2024-05-11 09:06 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoForOut.java
> +    protected Integer id;
Исправил.

2024-05-11 09:07 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoForIn.java
> +    protected Integer itemId;
Исправил.

2024-05-11 09:07 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/Item.java
>      protected int id;
Исправил.

2024-05-11 09:07 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      public ItemDto add(@RequestHeader("X-Sharer-User-Id") Integer ownerId,
Исправил.

2024-05-11 09:07 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
Исправил.

2024-05-11 16:02 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (item.getOwner().getId() == bookerId) throw new NoSuchElementException("Владелец не может бронировать свои вещи");
Исправлено.

2024-05-11 16:05 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        } catch (EntityNotFoundException e) {
Конструкции  try-catch везде убрал. В реализации ошибка обрабатывается в ErrorHandler с возвратом в контроллер нужного кода ошибки.

2024-05-11 16:08 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +public class BookingService {
Добавил везде, где данные чтения передаются в контроллер.

2024-05-11 16:10 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/user/UserService.java
>  public class UserService {
Добавил везде, где данные чтения передаются в контроллер.

2024-05-11 16:10 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/ItemService.java
>  public class ItemService {
Добавил везде, где данные чтения передаются в контроллер.

2024-05-11 16:16 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private final BookingRepository bookingStorage;
Исправлено, кроме внедрения ItemRepository в BookingService. 
Если исправить и тут, приложение не запускается из-за циклической зависимости.

2024-05-12 10:34 UTC, db-exp requested changes

2024-05-12 10:34 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +public class BookingService {
на остальные методы с записью нужно просто Transactional без readOnly на запись/чтение

2024-05-12 10:34 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemService.java
>      public ItemDto add(int ownerId, ItemDto itemDto) {
на остальные методы с записью нужно просто Transactional без readOnly на запись/чтение

2024-05-12 10:34 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemService.java
>      public ItemDto add(int ownerId, ItemDto itemDto) {
на остальные публичные методы, Transactional внутри Transactional делать не нужно

2024-05-12 11:31 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +public class BookingService {
Исправлено.

2024-05-12 11:31 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/item/ItemService.java
>      public ItemDto add(int ownerId, ItemDto itemDto) {
Исправлено.

2024-05-13 09:22 UTC, db-exp approved these changes

2024-05-13 09:33 UTC, merged