Add item requests
KurakinPavel/java-shareit pull request #3
Opened 2024-05-21 07:05 UTC by KurakinPavel

2024-05-21 15:42 UTC, db-exp requested changes

2024-05-21 15:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/model/ItemRequestDtoIn.java
> +    protected String description;
лучше оставить только что-то одно, и , если NotBlank, то и Size добавить можно

2024-05-21 16:10 UTC, KurakinPavel commented on src/main/java/ru/practicum/shareit/request/model/ItemRequestDtoIn.java
> +    protected String description;
Исправлено.

2024-05-22 10:31 UTC, db-exp approved these changes

2024-05-22 13:42 UTC, merged