Add docker
KurakinPavel/java-shareit pull request #5
Opened 2024-06-01 14:12 UTC by KurakinPavel

2024-06-02 22:07 UTC, db-exp requested changes

2024-06-02 22:07 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotNull
и NotNull и NotBlank смысла особо нет - NotBlank умеет и NotNull и проверку на пустоту

2024-06-02 22:07 UTC, db-exp commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
лучше брать из docker-compose - ${ИМЯ_ПЕРЕМЕННОЙ}

2024-06-02 22:07 UTC, db-exp commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
лучше брать из docker-compose - ${ИМЯ_ПЕРЕМЕННОЙ}

2024-06-03 09:48 UTC, KurakinPavel commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotNull
Исправлено во всех dto.

2024-06-03 09:49 UTC, KurakinPavel commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
Исправлено.

2024-06-03 09:49 UTC, KurakinPavel commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
Исправлено.

2024-06-03 10:07 UTC, db-exp approved these changes

2024-06-03 15:33 UTC, merged